In [1]:
import numpy as np

# Ejercicios

In [31]:
# Matriz singular: su determinante es cero
# There is one important theorem on singular matrix that can actually be used to generate a singular matrix and the theorem says: "The product of two matrices A = [A]n × k and B = [B]k × n (where n > k) is a matrix AB of order n × n and is always singular". By this theorem:

# The product AB of two matrices A of order n × 1 and B of order 1 × n is singular always.
# The product AB of two matrices A of order n × 2 and B of order 2 × n is also singular, etc.
# Using this theorem, one can generate a singular matrix by multiplying two randomly generated matrices of orders n × k and k × n where n > k.

A = np.random.randint(5, size=(5, 4))
print("A =" , A)
print(A.shape)
B = np.random.randint(5, size=(4, 5))
print("B =" , B)
print(B.shape)
AB = np.matmul(A, B)
print("AB =" , AB)
np.linalg.det(AB) # determinante cero


A = [[3 0 1 0]
 [2 1 2 4]
 [4 3 3 3]
 [4 3 2 0]
 [0 2 1 4]]
(5, 4)
B = [[3 1 1 3 2]
 [0 2 3 1 2]
 [3 4 1 1 4]
 [1 0 4 3 3]]
(4, 5)
AB = [[12  7  4 10 10]
 [16 12 23 21 26]
 [24 22 28 27 35]
 [18 18 15 17 22]
 [ 7  8 23 15 20]]


np.float64(0.0)

In [19]:
A = np.random.randint(5, size=(5, 4))
print("A =" , A)
print(A.shape)
B = np.random.randint(5, size=(4, 5))
print("B =" , B)
print(B.shape)
AB = np.matmul(A, B)
print("AB =" , AB)
np.linalg.det(AB) # determinante cero

np.float64(0.0)

In [33]:
4*np.eye(4)

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

In [34]:
import cv2